### ISSUE TITLE
Issue with assert 1.6.2

### ISSUE THREAD

**Issue by larends** [learn-co-curriculum/dsc-sql-lab#1]
The code in the solution does not pass the assert.

**Comment by dan-rl1976** [comment]
There are two instances where I believe the assertions are incongruent with the directions. 

In query 7, the directions specify that the results be displayed in descending order, but the assertion expects ascending.

In query 8, the order of the columns is ambiguous in the instructions, and the assertion checks for the columns in different order than expected.

**Comment by jessepisel** [comment]
Thanks for raising this issue @larends :wave:. I have addressed this issue in more detail in #2 with commit ee9b15ad2af0dcfd826a14c1f4db79b10aed04eb.

I am closing this issue at this time.
