### ISSUE TITLE
Assertions do not follow instructions.

### ISSUE THREAD

**Issue by dan-rl1976** [learn-co-curriculum/dsc-sql-lab#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4339/modules/items/276165

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

1.6.4 Query 7:

From the markdown: 
"Sort the rows in descending order by the quantity ordered,"

From the assertion: 
`# Testing the values in the first result
assert list(q7_result.iloc[0]) == ['Petit Auto', 314, '1913 Ford Model T Speedster', 'S18_2949', 10]` 

Similar issue in 1.6.5 Query 8:

From the markdown:
"get the first name, last name, employee number, and office code for employees from offices with fewer than 5 employees."

From the assertion:
`# Testing which columns are returned
assert list(q8_result.columns) == ['lastName', 'firstName', 'employeeNumber', 'officeCode']`

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X

**Comment by jessepisel** [comment]
Thanks for opening this issue @dan-rl1976 :wave:. I have updated the instructions for clarity in commit ee9b15ad2af0dcfd826a14c1f4db79b10aed04eb. The query 7 assertion needed the data in ascending order rather than descending. The instructions for query 8 now match the ordering for the column assertion.

I am closing this issue at this time.
