### ISSUE TITLE
Questions with JOIN just use 'JOIN' on the solutions but the directions on the non-solution branch says use a simple LEFT JOIN 

### ISSUE THREAD

**Issue by aspratle** [learn-co-curriculum/dsc-sql-lab#8]
Can we check that we want the JOIN questions (5 to 8) to just have JOIN or use LEFT JOINS. For question #5 students are told to use LEFT join but that doesn't work (doesn't pass assert) the solution just has JOIN.  

## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by aspratle** [comment]
All information is above

**Comment by jessepisel** [comment]
thanks for flagging this issue :wave:. I have updated all the branches to reflect the students should just use `JOIN` instead of `LEFT JOIN` in commit [043608a](https://github.com/learn-co-curriculum/dsc-sql-lab/commit/043608acf619d757b78d9539a4b977b8f0456d46).
